### ISSUE TITLE
Project directory and documentation comments

### ISSUE THREAD

**Issue by Glenn032787** [bcgsc/Canadian_Biogenome_Project#1]
Hey Solenne! The pipeline looks great, I just have some suggestions for documentation and project directory structure. The one marked as complete are ones that are in the glennSuggestion branch.

Comments:
- [X]  Just a suggestion to have a `example_input` and `src` directory for the example fastq/bam files and workflow image respectively.
- [X] Would be good to include a MIT or CC license
- [X] In the ReadMe, I would suggest including either the Github page or the command to install programs that require local installation.  
- [X] Change hyperlink for the URL in the readme to make it look more clean
- [ ] #3
- [x] I am not sure what the best practice for nextflow is but it might be good to separate the config files to inputs and parameter config files 
- [x] Might be good to include a copy of JuicerTools.jar to the repo? That is what I did in my workflow, it doesn't take up much space but I am not sure if this is best practice.
- [ ] #5
- [x] Might be good to suggest minimum memory and time it takes to run since it is a memory/time intensive program (or add a warning saying a step is expected to take a longer time)

**Comment by scorreard** [comment]
Hi Glenn,

Sorry for the delay, I am working on that on the new release.
- Splitting the config file : We usually don't with nextflow, having one config file is easier and loaded automatically
- JuicerTools.jar : Juicer is no longer a mandatory step in the pipeline, I now use pretext for HiC maps, so it shouldn't crash the pipeline.
- Memory and time for each module (step) are included in the config file, I don't think an additional warning is necessary.

I will try "Running the pipeline with test data" for the new release and if it fails, I will change it to an issue.

Thanks again!

**Comment by scorreard** [comment]
Closing the issue as the two remaining tasks have been changed to issues
